# Generated by Django 4.2.9 on 2024-01-27 21:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
                ),
                ("audio", models.FileField(upload_to="audios")),
                ("transcription_en", models.TextField(blank=True)),
                ("transcription_original", models.TextField(blank=True)),
                ("file_location", models.CharField(editable=False, max_length=255)),
                ("upload_timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "id",
                    models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("file_location", models.CharField(blank=True, editable=False, max_length=255)),
                ("upload_timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_message_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.audiofile"),
                ),
                ("chat_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.chat")),
                (
                    "image_id",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.imagefile"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["chat_id"], name="chat_id_idx"),
                    models.Index(fields=["timestamp"], name="timestamp_idx"),
                    models.Index(fields=["chat_id", "timestamp"], name="chat_id_timestamp_idx"),
                ],
            },
        ),
    ]
