# Generated by Django 4.2.9 on 2024-03-06 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_owner", models.BooleanField(default=False)),
                ("has_read_access", models.BooleanField(default=True)),
                ("has_write_access", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.chat")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="chat",
            name="participants",
            field=models.ManyToManyField(through="api.Participant", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(fields=["chat"], name="chat_participant_idx"),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(fields=["user"], name="user_participant_idx"),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(fields=["chat", "user"], name="chat_user_participant_idx"),
        ),
    ]
