# Generated by Django 4.2.9 on 2024-03-06 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_participant_chat_participants_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("has_read_access", models.BooleanField(default=True)),
                ("has_write_access", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="chat",
            name="participants",
        ),
        migrations.AddField(
            model_name="chat",
            name="owner",
            field=models.ForeignKey(
                default=3,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="owner",
            field=models.ForeignKey(
                default=3,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_message_owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="chat",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.chat"),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["chat"], name="chat_participant_idx"),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["user"], name="user_participant_idx"),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["chat", "user"], name="chat_user_participant_idx"),
        ),
    ]
