# Generated by Django 4.2.9 on 2024-03-06 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_chatparticipant_remove_chat_participants_chat_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="participants",
            field=models.ManyToManyField(through="api.ChatParticipant", to=settings.AUTH_USER_MODEL),
        ),
    ]
