# Generated by Django 4.2.9 on 2024-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_chat_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="ai_tips",
            field=models.TextField(blank=True),
        ),
    ]
