apiVersion: v1
data:
  POSTGRES_DB: babblebox
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: test
  POSTGRES_PORT: "5432"
  POSTGRES_USER: test
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: celerybeat--postgres
  name: postgresc
