apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f production.yml -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: awscli
  name: awscli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: awscli
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f production.yml -o k8s
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/babblebox-default: "true"
        io.kompose.service: awscli
    spec:
      containers:
        - env:
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_PASSWORD
                  name: djangoc
            - name: CELERY_FLOWER_USER
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_USER
                  name: djangoc
            - name: DJANGO_ACCOUNT_ALLOW_REGISTRATION
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ACCOUNT_ALLOW_REGISTRATION
                  name: djangoc
            - name: DJANGO_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ADMIN_URL
                  name: djangoc
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ALLOWED_HOSTS
                  name: djangoc
            - name: DJANGO_AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_ACCESS_KEY_ID
                  name: djangoc
            - name: DJANGO_AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_SECRET_ACCESS_KEY
                  name: djangoc
            - name: DJANGO_AWS_STORAGE_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_STORAGE_BUCKET_NAME
                  name: djangoc
            - name: DJANGO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: djangoc
            - name: DJANGO_SECURE_SSL_REDIRECT
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECURE_SSL_REDIRECT
                  name: djangoc
            - name: DJANGO_SERVER_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SERVER_EMAIL
                  name: djangoc
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SETTINGS_MODULE
                  name: djangoc
            - name: MAILJET_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAILJET_API_KEY
                  name: djangoc
            - name: MAILJET_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAILJET_SECRET_KEY
                  name: djangoc
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: djangoc
            - name: WEB_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  key: WEB_CONCURRENCY
                  name: djangoc
          image: awscli
          name: awscli
          volumeMounts:
            - mountPath: /backups
              name: production-postgres-data-backups
      restartPolicy: Always
      volumes:
        - name: production-postgres-data-backups
          persistentVolumeClaim:
            claimName: production-postgres-data-backups
