apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f production.yml -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: celeryworker
  name: celeryworker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celeryworker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f production.yml -o k8s
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/babblebox-default: "true"
        io.kompose.service: celeryworker
    spec:
      containers:
        - args:
            - /start-celeryworker
          env:
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_PASSWORD
                  name: djangoc
            - name: CELERY_FLOWER_USER
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_USER
                  name: djangoc
            - name: DJANGO_ACCOUNT_ALLOW_REGISTRATION
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ACCOUNT_ALLOW_REGISTRATION
                  name: djangoc
            - name: DJANGO_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ADMIN_URL
                  name: djangoc
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_ALLOWED_HOSTS
                  name: djangoc
            - name: DJANGO_AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_ACCESS_KEY_ID
                  name: djangoc
            - name: DJANGO_AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_SECRET_ACCESS_KEY
                  name: djangoc
            - name: DJANGO_AWS_STORAGE_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_AWS_STORAGE_BUCKET_NAME
                  name: djangoc
            - name: DJANGO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: djangoc
            - name: DJANGO_SECURE_SSL_REDIRECT
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECURE_SSL_REDIRECT
                  name: djangoc
            - name: DJANGO_SERVER_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SERVER_EMAIL
                  name: djangoc
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SETTINGS_MODULE
                  name: djangoc
            - name: MAILJET_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAILJET_API_KEY
                  name: djangoc
            - name: MAILJET_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAILJET_SECRET_KEY
                  name: djangoc
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgresc
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgresc
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgresc
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: postgresc
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgresc
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: djangoc
            - name: WEB_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  key: WEB_CONCURRENCY
                  name: djangoc
          image: 058264340712.dkr.ecr.us-east-1.amazonaws.com/babblebox_production_celeryworker
          name: celeryworker
      restartPolicy: Always
