apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: production-postgres-data-backups
  name: production-postgres-data-backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
