apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: production-traefik
  name: production-traefik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
