apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f production.yml -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  type: LoadBalancer  # Added line for LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "5555"
      port: 5555
      targetPort: 5555
  selector:
    io.kompose.service: traefik
