apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f production.yml -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f production.yml -o k8s
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/babblebox-default: "true"
        io.kompose.service: traefik
    spec:
      containers:
        - image: 058264340712.dkr.ecr.us-east-1.amazonaws.com/babblebox_production_traefik
          name: traefik
          ports:
            - containerPort: 80
              hostIP: 0.0.0.0
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostIP: 0.0.0.0
              hostPort: 443
              protocol: TCP
            - containerPort: 5555
              hostIP: 0.0.0.0
              hostPort: 5555
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/traefik/acme
              name: production-traefik
      restartPolicy: Always
      volumes:
        - name: production-traefik
          persistentVolumeClaim:
            claimName: production-traefik
