version: '3'

volumes:
  babblebox_local_postgres_data: {}
  babblebox_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: babblebox_local_django
    container_name: babblebox_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: babblebox_production_postgres
    container_name: babblebox_local_postgres
    volumes:
      - babblebox_local_postgres_data:/var/lib/postgresql/data
      - babblebox_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'

  mailpit:
    image: axllent/mailpit:latest
    container_name: babblebox_local_mailpit
    ports:
      - "8025:8025"

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: babblebox_local_node
    container_name: babblebox_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '5173:5173'

  network-debug:
    image: nicolaka/netshoot  # A popular network troubleshooting image
    command: sleep infinity
