version: '3'

volumes:
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: ${DOCKER_REGISTRY}/babblebox_production_django
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - '5001:5000'


  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: ${DOCKER_REGISTRY}/babblebox_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'
