# Generated by Django 4.2.9 on 2024-05-02 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_username_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="username_idx",
        ),
    ]
